sudo: false
language: ruby 

rvm:
  - 2.3.5
  - 2.4.2
  - 2.5.3
  - 2.6.1
  - ruby-head

cache:
  bundler: true 
  directories:
    - node_modules
  yarn: true

install:
  - gem install bundler
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn 
  - yarn

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database grandham_test;'
  - RAILS_ENV=test bundle exec rake db:migrate
  - yarn 

script:
  - bundle exec rake test
  - bundle exec rake spec
  - bundle exec rubocop

notifications:
  email:
    - ershad92@gmail.com
    - aboobackervyd+grandham@gmail.com
