language = Language.where(name: 'Malayalam', short_code: 'ML', default: true).first_or_create!

fields = [["ISBN", "isbn"],
          ["DDC", "ddc"],
          ["Publisher subject category", "publisher_subject_category"],
          ["Original language if translation", "original_language_if_translation"],
          ["Book No.1", "book_no_1"],
          ["Book No.2", "book_no_2"],
          ["Author 1, Personal, Main", "author_1_personal_main"],
          ["Author 1, Personal, Main - Role", "author_1_personal_main_role"],
          ["Author 1, Corporate, Main", "author_1_corporate_main"],
          ["Author 2, Personal, Added", "author_2_personal_added"],
          ["Author 2, Personal, Added - Role", "author_2_personal_added_role"],
          ["Author 3, Personal, Added", "author_3_personal_added"],
          ["Author 3, Personal, Added - Role", "author_3_personal_added_role"],
          ["Title (sub-title included)", "title_sub_title_included"],
          ["Volume/Part", "volume_part"],
          ["Edition", "edition"],
          ["SOR (Statement of responsibility- Author", "sor_statement_of_responsibility_author"],
          ["Real Name- Author", "real_name_author"],
          ["Publisher", "publisher"],
          ["Place", "place"],
          ["Year", "year"],
          ["Series", "series"],
          ["Series No.", "series_no"],
          ["Number of Volumes", "number_of_volumes"],
          ["Pages", "pages"],
          ["Price", "price"],
          ["Dimensions (LengthXwidth)", "dimensions_lengthxwidth"],
          ["Subject KW1", "subject_kw1"],
          ["Subject KW2", "subject_kw2"],
          ["Subject KW3", "subject_kw3"],
          ["Note/Abstract", "note_abstract"],
          ["Rewies/ comments by Readers", "rewies_comments_by_readers"],
          ["Title Org", "title_org"],
          ["Preface", "preface"],
          ["Illustrator", "illustrator"],
          ["Length", "length"],
          ["Location", "location"]]

fields.each do |name, short_id|
  Field.where(name: name, short_id: short_id).first_or_create!
end