require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BookSubmissionsController do

  # This should return the minimal set of attributes required to create a valid
  # BookSubmission. As you add validations to BookSubmission, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "book_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BookSubmissionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all book_submissions as @book_submissions" do
      book_submission = BookSubmission.create! valid_attributes
      get :index, {}, valid_session
      assigns(:book_submissions).should eq([book_submission])
    end
  end

  describe "GET show" do
    it "assigns the requested book_submission as @book_submission" do
      book_submission = BookSubmission.create! valid_attributes
      get :show, {:id => book_submission.to_param}, valid_session
      assigns(:book_submission).should eq(book_submission)
    end
  end

  describe "GET new" do
    it "assigns a new book_submission as @book_submission" do
      get :new, {}, valid_session
      assigns(:book_submission).should be_a_new(BookSubmission)
    end
  end

  describe "GET edit" do
    it "assigns the requested book_submission as @book_submission" do
      book_submission = BookSubmission.create! valid_attributes
      get :edit, {:id => book_submission.to_param}, valid_session
      assigns(:book_submission).should eq(book_submission)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BookSubmission" do
        expect {
          post :create, {:book_submission => valid_attributes}, valid_session
        }.to change(BookSubmission, :count).by(1)
      end

      it "assigns a newly created book_submission as @book_submission" do
        post :create, {:book_submission => valid_attributes}, valid_session
        assigns(:book_submission).should be_a(BookSubmission)
        assigns(:book_submission).should be_persisted
      end

      it "redirects to the created book_submission" do
        post :create, {:book_submission => valid_attributes}, valid_session
        response.should redirect_to(BookSubmission.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved book_submission as @book_submission" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookSubmission.any_instance.stub(:save).and_return(false)
        post :create, {:book_submission => { "book_id" => "invalid value" }}, valid_session
        assigns(:book_submission).should be_a_new(BookSubmission)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BookSubmission.any_instance.stub(:save).and_return(false)
        post :create, {:book_submission => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested book_submission" do
        book_submission = BookSubmission.create! valid_attributes
        # Assuming there are no other book_submissions in the database, this
        # specifies that the BookSubmission created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BookSubmission.any_instance.should_receive(:update_attributes).with({ "book_id" => "1" })
        put :update, {:id => book_submission.to_param, :book_submission => { "book_id" => "1" }}, valid_session
      end

      it "assigns the requested book_submission as @book_submission" do
        book_submission = BookSubmission.create! valid_attributes
        put :update, {:id => book_submission.to_param, :book_submission => valid_attributes}, valid_session
        assigns(:book_submission).should eq(book_submission)
      end

      it "redirects to the book_submission" do
        book_submission = BookSubmission.create! valid_attributes
        put :update, {:id => book_submission.to_param, :book_submission => valid_attributes}, valid_session
        response.should redirect_to(book_submission)
      end
    end

    describe "with invalid params" do
      it "assigns the book_submission as @book_submission" do
        book_submission = BookSubmission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookSubmission.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_submission.to_param, :book_submission => { "book_id" => "invalid value" }}, valid_session
        assigns(:book_submission).should eq(book_submission)
      end

      it "re-renders the 'edit' template" do
        book_submission = BookSubmission.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BookSubmission.any_instance.stub(:save).and_return(false)
        put :update, {:id => book_submission.to_param, :book_submission => { "book_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested book_submission" do
      book_submission = BookSubmission.create! valid_attributes
      expect {
        delete :destroy, {:id => book_submission.to_param}, valid_session
      }.to change(BookSubmission, :count).by(-1)
    end

    it "redirects to the book_submissions list" do
      book_submission = BookSubmission.create! valid_attributes
      delete :destroy, {:id => book_submission.to_param}, valid_session
      response.should redirect_to(book_submissions_url)
    end
  end

end
